use_frameworks!

target 'Trolley_Example' do
  pod 'Trolley', :path => '../'

  target 'Trolley_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'PromiseKit'
    pod 'SwiftyJSON'
    pod 'Nimble', '~> 5.1.1'
    pod 'Trolley', :path => '../'
  end
  
end
