platform :ios, '10.3'
use_frameworks!

target 'Trolley_Example' do
  pod 'Trolley', :path => '../'
  pod 'Trolley/Database', :path => '../'
  pod 'Trolley/Delivery', :path => '../'
  pod 'Trolley/Notification', :path => '../'

  target 'Trolley_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'Trolley', :path => '../'
    pod 'Trolley/Database', :path => '../'
    pod 'Trolley/Delivery', :path => '../'
    pod 'Trolley/Notification', :path => '../'
  end

end
