# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
branches:
    only:
        - master
        - travis-ci
before_install:
    - rvm install ruby-2.2.2
    - gem install cocoapods
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty-travis-formatter
    - pod install --project-directory=Example

    # Workaround for Error 65
    - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 7 (10.3.1" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
    - echo $IOS_SIMULATOR_UDID
    - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
    # travis_retry is a workaround for Error 65
    - set -o pipefail && travis_retry xcodebuild test -workspace Example/Trolley.xcworkspace -scheme Trolley-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' ONLY_ACTIVE_ARCH=NO | xcpretty -f `xcpretty-travis-formatter`
    - pod lib lint Trolley.podspec --verbose
