# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
branches:
    only:
        - master
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N

xcode_workspace: Example/Trolley.xcworkspace
xcode_scheme: Trolley_Tests
xcode_sdk: iphonesimulator10.3
# # cache: cocoapods
# # podfile: Example/Podfile
# # before_install:
# # - gem install cocoapods # Since Travis is not always on latest version
# # - pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -workspace Example/Trolley.xcworkspace -scheme Trolley-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
