#!/usr/bin/env sh

set -o pipefail && xcodebuild test -workspace Example/Trolley.xcworkspace -scheme Trolley-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' ONLY_ACTIVE_ARCH=NO | xcpretty

pod lib lint Trolley.podspec --verbose
